### ISSUE TITLE
Fastq files are not fully read

### ISSUE THREAD

**Issue by tzeitim** [wheretrue/biobear#89] opened 2024-01-27 18:28 UTC
I am trying to read a fastq.gz file and convert into a polars data frame but no matter what fastq file I chose, the number of lines read are just small set that more or less scales up with the length of the read. For example, in files with shorter reads (28bp) I can open up to ~600 entries; ~250 some with longer (100) ones.

It seems to me as if there is a limit of bytes being read that caps the reader.

```
import biobear as bb
from biobear.compression import Compression

# an example with short reads
for file in files:
    print(bb.FastqReader(file, compression=Compression.GZIP).to_polars().shape)
(591, 4)
(591, 4)
(591, 4)
(589, 4)
(592, 4)
(591, 4)
(591, 4)
(591, 4)
(591, 4)
(591, 4)
(591, 4)
(591, 4)
(591, 4)
(591, 4)
```

**Comment by tshauck** [comment] 2024-01-27 18:32
Hi, sorry it's giving you trouble. Let me have a look and I'll follow up.

**Comment by tshauck** [comment] 2024-01-27 18:52
@tzeitim Do you think you could share an example including a file? Unfortunately, I'm having trouble reproducing this issue.

I tried one of the FASTQ's here (https://zenodo.org/records/3736457) and one generated randomly[1] with read lengths between 20 and 60. Both of which seem to not be maxxed out at 591 (or some other subset of the overall reads).

[1] Random FASTQ Script

```python
import random
import subprocess


def generate_sequence(length):
    return "".join(random.choice("ACGT") for _ in range(length))


def generate_quality_scores(length):
    # In real FASTQ files, these are ASCII characters representing quality.
    # Here, we'll just use a simple placeholder character.
    return "I" * length


def generate_fastq_entry():
    seq_length = random.randint(20, 60)
    sequence = generate_sequence(seq_length)
    quality_scores = generate_quality_scores(seq_length)
    return f"@random_sequence\n{sequence}\n+\n{quality_scores}\n"


def generate_fastq_file(filename, num_reads):
    with open(filename, "w") as file:
        for _ in range(num_reads):
            file.write(generate_fastq_entry())


# Example usage
generate_fastq_file(
    "fake_fastq_file.fastq", 20000
)  # Change 100 to desired number of reads

subprocess.run(["gzip", "fake_fastq_file.fastq"])

```

Then, BioBear to read

```python
import biobear as bb
from biobear.compression import Compression

df = bb.FastqReader(
    "fake_fastq_file.fastq.gz", compression=Compression.GZIP
).to_polars()

print(df.shape)

# print the average length of the sequence column
print(df["sequence"].str.len_chars().mean())
```

Which prints 

```
python gen-biobear-test.py
(20000, 4)
39.92005
```

That agrees with seqkit

```
seqkit stats fake_fastq_file.fastq.gz 
file                      format  type  num_seqs  sum_len  min_len  avg_len  max_len
fake_fastq_file.fastq.gz  FASTQ   DNA     20,000  798,401       20     39.9       60
```

**Comment by tzeitim** [comment] 2024-01-27 18:54
Thanks for your quick reply. Let me create a link on dropbox.

**Comment by tzeitim** [comment] 2024-01-27 19:03
Here a couple paired-end files: [R1](https://www.dropbox.com/scl/fi/j4cuo2zzco9rhzh7hf4ep/G10_0min_0pulses_A_S1_R1_001.fastq.gz?rlkey=slfda4qp72mspivtte24l643v&dl=1) and [R2](https://www.dropbox.com/scl/fi/o9xvf1gh7z4pe7tjn5fl7/G10_0min_0pulses_A_S1_R2_001.fastq.gz?rlkey=rsyrijwjkn465iip8ac0hvqvr&dl=1)

**Comment by tshauck** [comment] 2024-01-27 19:06
Thanks! I can repro with these files. I'll follow up when I know more.

**Comment by tzeitim** [comment] 2024-01-27 19:10
Thanks again. It is late in this side of the planet so I might not be so responsive for the next hours.

**Comment by tshauck** [comment] 2024-01-27 21:22
Looks like the root cause was due to the gzip decoder not properly handling bgzip files. I think this is actually an issue w/ the underlying library, but to solve the issue now I've put in a code path to sniff for the bgzip header, then use it if appropriate. I'll try to track down the library issue separately.

That seems to resolve the issue on my computer with those files:
<img width="1075" alt="image" src="https://github.com/wheretrue/biobear/assets/421839/1f1d858e-82ee-4055-af0f-f2c2f2076dd8">

I've started the release process for [Exon](https://github.com/wheretrue/exon) that underlies biobear, and will do biobear when that's done. Due to the complication the build time can take a while, but if all goes well it should be a couple of hours. I'll follow up here when it's ready for another look.

**Comment by tshauck** [comment] 2024-01-28 00:30
I think things've matriculated to pypi, and I think this is handled ok now 🤞 , but please let me know:
<img width="1017" alt="image" src="https://github.com/wheretrue/biobear/assets/421839/b8d967a4-fde4-405c-827a-17fcaf8bcd94">

(I also moved `Compression` to also be under the root import, to make it a little more ergonomic)

**Comment by tzeitim** [comment] 2024-01-28 04:13
Hi @tshauck, I confirm that files can be loaded correctly.

Thanks again for the fast response!

**Comment by tshauck** [comment] 2024-01-28 17:18
Great, thanks for giving it a shot and working through it. I'm gonna close this issue, but please open another one if you have another issue/question/feedback etc.

**Closed by tshauck** 2024-01-28 17:18 UTC
Labels: bug
